
version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-and-test:
    executor: python/default
    environment:
      DJANGO_SETTINGS_MODULE: "locallibrary.settings"
    steps:
      - checkout
      - python/load-cache
          key: v1
      - python/install-deps
      - python/save-cache
          key: v1
      - run:
          command: pytest

workflows:
  main:
    jobs:
      - build-and-test