
version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-and-test:
    executor: python/default
    environment:
      DJANGO_SETTINGS_MODULE: "locallibrary.settings"
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python --version
      - run:
          command: pytest --version
      - run:
          command: pytest
      - run:
          command: python manage.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test